### ISSUE TITLE
"scene" and "warp" commands

### ISSUE THREAD

**Issue by ZagoraMi** [360NENZ/LDAsuku-soggy#5]
Many CBT 1 gameplay videos and articles mention commands called "scene" and "warp" using soggy. But in this soggy they are absent. What should I do to make these commands appear?
![изображение](https://github.com/360NENZ/LDAsuku-soggy/assets/60652339/e5f8b2b2-459e-4cef-aae6-de6a74658287)

**Comment by vrad-exe** [comment]
You have to build it yourself from source, the version in the releases tab is out of date

**Comment by a-name-real** [comment]
Upon building with MSYS2 MINGW64, i get constant errors like
binpack.cpp:56:29: error: 'uint8_t' was not declared in this scope
binpack.cpp:56:36: error: template argument 1 is invalid
make[2]: *** [CMakeFiles/soggy_binpack.dir/build.make:76: CMakeFiles/soggy_binpack.dir/tool/binpack.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/soggy_binpack.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target soggy_proto
make: *** [Makefile:136: all] Error 2

Can you update the compiled build in releases? Because I have no clue what I'm doing wrong.

**Comment by H2102M** [comment]
> Upon building with MSYS2 MINGW64, i get constant errors like binpack.cpp:56:29: error: 'uint8_t' was not declared in this scope binpack.cpp:56:36: error: template argument 1 is invalid make[2]: *** [CMakeFiles/soggy_binpack.dir/build.make:76: CMakeFiles/soggy_binpack.dir/tool/binpack.cpp.obj] Error 1 make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/soggy_binpack.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... [100%] Built target soggy_proto make: *** [Makefile:136: all] Error 2
> 
> Can you update the compiled build in releases? Because I have no clue what I'm doing wrong.

Try adding "#include <stdint.h>" in the LDAsuku-soggy/tool/binpack.cpp
```

// binpack.cpp

#include <cassert>
#include <fstream>
#include <iomanip>
#include <iterator>
#include <sstream>
#include <string>
#include <vector>

#include <stdint.h> //Here

```
